#FROM docker.artifactory-preprod.a.intuit.com/oicp/tomcat:latest
FROM tomcat:latest
MAINTAINER earl_waud@intuit.com

#/usr/local/apache-tomcat-8.0.36H-2.0.1/webapps/ROOT.war

EXPOSE 8080

CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]

